config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'home', to: 'home#home'
  get '', to: 'home#home'
  post 'result', to: 'result#product'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def home
    end
end

app/controllers/result_controller.rb
class ResultController < ApplicationController
    def product
        @city = params[:location]
        loc = ''
        val = Geocoder.search(@city)
        if val[0] != nil
            loc = val.first.city + ',' + val.first.country
            loc = loc.downcase
            if val.first.country.downcase == "chile" and val.first.city.downcase == "santiago"
                loc = "santiago,cl"
            end
        else
            flash[:failure] = "City or country not found"
            redirect_to controller: 'home', action: 'home'
        end
        #history es con suscripcion pagada
        @las = val.first.city
        weatherjson = 'http://api.openweathermap.org/data/2.5/weather?q=' + loc  + '&appid=b4344374965e420e9ad7109ad84b7f00'
        weat = HTTParty.get(weatherjson)
        @weather = JSON.parse(weat.body)#conseguir la temperatura promedio
        # check = JSON.parse(weat.headers.inspect)

        # if check["cod"] == "404"
        #     flash[:failure] = "City or country not found"
        #     redirect_to controller: 'home', action: 'home'
        # end
        @w = @weather["weather"]
        @dayg = @w[0]["main"]#tiempo
        @day = @w[0]["description"]#descripcion tiempo
        @temp1 = @weather["main"] #
        @temp = @temp1["temp"].to_i - 273 #temperatura

        @opcion = 0 #sumar 7 para siguiente producto
        if params[:card].to_i
            @opcion = params[:card].to_i
            if @opcion == 5
                @opcion = 0
            end
        end 
        require 'openssl'
        require 'open-uri'
        urls = ''
        if @temp < 5
            urls = "https://www.dafiti.cl/femenino/vestuario/parkas/"
        elsif @temp >= 5 and @temp < 18
            urls = "https://www.dafiti.cl/femenino/trench/"
        elsif @temp >= 18 and @temp < 23
            urls = "https://www.dafiti.cl/femenino/vestuario/chalecos-y-sweaters/"
        elsif @temp > 23
            urls = "https://www.dafiti.cl/femenino/vestuario/blusas/"
        end
        doc = Nokogiri::HTML(open(urls, :ssl_verify_mode => OpenSSL::SSL::VERIFY_NONE))
        entries = doc.css('.productsCatalog')
        i = 0
        ra = []
        while i < 5
            be = entries.css('li')[i*7]
            ra.push(be)
            i = i + 1
        end
        ra.each do |r|
            r.search('.itm-product-addcard-box').each do |s|
                s.remove
            end
            r.search('.itm-price-installments').each do |s|
                s.remove
            end
            r.search('.itm-priceBox').each do |s|
                s.remove
            end
            r.search('.itm-free-shipping').each do |s|
                s.remove
            end
            r.search('.itm-saleFlagPercent').each do |s|
                s.remove
            end
        end
        @rate = ra[@opcion]
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/result_helper.rb
module ResultHelper
end

app/views/home/home.html.erb
<%= form_tag(result_path) do %>
    <tr>Ingresar ciudad seguido de una coma por el pais para tener una mejor precision</tr>
    <%= text_field_tag :location %>
    <%= submit_tag 'Buscar', :class => "btn btn-primary btn-md" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weatherdrobe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

    <script src="https://dafitistaticcl-a.akamaihd.net/js/live/control-a3d74937f4.js"></script>
    <script src="https://dafitistaticcl-a.akamaihd.net/js/live/desktop-head-24371af6db.js"></script>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/result/product.html.erb
<div>
    <p>City: <%= @las %></p>
    <p>Overall Description: <%= @dayg %></p>
    <p>Description: <%= @day %></p>
    <p>Temperature: <%= (@temp) %></p>
    <p></p>
    <p></p>
    <p></p>
    <div>
        <%= raw @rate %>
    </div>
    <%= button_to "Next", result_path(:location => @city, :card => (@opcion+1))%>

    
</div>